name: Critical Event Detection
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: enriched-data
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: danger_condition
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
libraryItemId: event-detection-transformation
