name: PostgreSQL Raw Data Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: danger_condition
    required: true
  - name: POSTGRES_HOST
    inputType: FreeText
    description: Host address for the PostgreSQL instance.
    required: true
  - name: POSTGRES_PORT
    inputType: FreeText
    description: Port number for the PostgreSQL instance.
    required: true
  - name: POSTGRES_DBNAME
    inputType: FreeText
    description: Database name in PostgreSQL where data should be stored.
    required: true
  - name: POSTGRES_USER
    inputType: FreeText
    description: Username for the PostgreSQL database.
    required: true
  - name: POSTGRES_PASSWORD
    inputType: Secret
    description: Password for the PostgreSQL database.
    required: true
  - name: POSTGRES_TABLE
    inputType: FreeText
    description: The PostgreSQL table where danger condition data will be stored.
    required: true
  - name: POSTGRES_SCHEMA
    inputType: FreeText
    description: The schema name.
  - name: SCHEMA_AUTO_UPDATE
    inputType: FreeText
    description: Automatically update the schema.
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    description: The name of the consumer group to use when consuming from Kafka
    required: true
  - name: BATCH_SIZE
    inputType: FreeText
    description: The number of records that the sink holds before flushing data to PostgreSQL.
  - name: BATCH_TIMEOUT
    inputType: FreeText
    description: The number of seconds that the sink holds before flushing data to PostgreSQL.
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: postgresql-destination
